name: Node.js Deployment with NGINX and SSL

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            # Go to the client (admin) directory
            cd /var/www/html/saas/admin

            # Fetch the latest changes from the Git repository
            git fetch --all
            git reset --hard origin/main

            # Setup environment and dependencies
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            npm install

            # Build the React application for production
            npm run build

            # Copy the build files to the Nginx public directory
            rm -rf /var/www/html/saas/admin/*  # Clear previous build files
            cp -r build/* /var/www/html/saas/admin/

            # If you want to restart Nginx to reflect changes (optional)
            sudo systemctl restart nginx

            # Optionally, restart PM2 or ensure the app is running in PM2
            # pm2 restart trust-auto-server  # If necessary for PM2 processes
